### ISSUE TITLE
Got this error when a new benchmarking is started after the previous is finished in zarr format and object storage

### ISSUE THREAD

**Issue by halehawk** [pangeo-data/benchmarking#42]
Benchmark starting with: 
	worker_per_node = 1,
	num_nodes = 1, 
	chunk_size = 64MB,
	chunking_scheme = temporal,
	chunk per worker = 10
	io_format = zarr
<xarray.Dataset>
Dimensions:  (lat: 320, lon: 384, time: 652)
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01 1980-01-02 ... 1981-10-13
  * lon      (lon) float64 -180.0 -179.1 -178.1 -177.2 ... 178.1 179.1 180.0
  * lat      (lat) float64 -90.0 -89.44 -88.87 -88.31 ... 88.31 88.87 89.44 90.0
Data variables:
    sst      (time, lon, lat) float64 dask.array<chunksize=(66, 384, 320), meta=np.ndarray>
Dataset total size: 640.95 MB

Computation done
Benchmark starting with: 
	worker_per_node = 1,
	num_nodes = 1, 
	chunk_size = 64MB,
	chunking_scheme = spatial,
	chunk per worker = 10
	io_format = zarr
<xarray.Dataset>
Dimensions:  (lat: 320, lon: 384, time: 652)
Coordinates:
  * time     (time) datetime64[ns] 1980-01-01 1980-01-02 ... 1981-10-13
  * lon      (lon) float64 -180.0 -179.1 -178.1 -177.2 ... 178.1 179.1 180.0
  * lat      (lat) float64 -90.0 -89.44 -88.87 -88.31 ... 88.31 88.87 89.44 90.0
Data variables:
    sst      (time, lon, lat) float64 dask.array<chunksize=(652, 111, 111), meta=np.ndarray>
Dataset total size: 640.95 MB

Traceback (most recent call last):
  File "./pangeobench", line 18, in <module>
    cli()
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./pangeobench", line 14, in cli
    runner.run()
  File "/glade/work/haiyingx/benchmarking/benchmarks/utils.py", line 224, in run
    op(ds, fs, io_format, root)
  File "/glade/work/haiyingx/benchmarking/benchmarks/ops.py", line 71, in writefile
    ds.compute()
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/client.py", line 2632, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/client.py", line 1931, in gather
    asynchronous=asynchronous,
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/client.py", line 1790, in _gather
    raise exception.with_traceback(traceback)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/core.py", line 1946, in __setstate__
    self.__init__(*state)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/core.py", line 156, in _load_metadata_nosync
    meta = decode_array_metadata(meta_bytes)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/meta.py", line 32, in decode_array_metadata
    meta = parse_metadata(s)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/meta.py", line 26, in parse_metadata
    meta = json_loads(s)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/site-packages/zarr/util.py", line 30, in json_loads
    return json.loads(ensure_text(s, 'ascii'))
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/glade/work/haiyingx/miniconda3/envs/pangeo-bench/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 24 column 1 (char 368)

**Comment by kmpaul** [comment]
@halehawk So, this looks like you are trying to write over an existing Zarr store?  Is that correct?

**Comment by halehawk** [comment]
It is a new zarr file writing to the same name of a deleting zarr store. Or
I shall use a different name for each benchmark even differing on chunking
schemes. @Kevin Paul <kpaul@ucar.edu>

**Comment by kmpaul** [comment]
Object store does not guarantee that delete will be completed on an object before you access it next.  So, you probably need to name the zarr stores based on a time-stamp, or similar, just to keep them different.  I'm almost positive this is the problem you are seeing.
